[32|tooling] run app with supervisord
supervisord is coool! it acts like a mini-systemd for the set of
processes we need to run our app. spins 'em all up in daemon mode and
lets us monitor / stop / restart them with a `ctl` interface.

side-effects:
* extract `signal-cli` scripts into own dir
* remove signal-cli systemd config step
* expose `CURRENT_USER` as arg to `signal-cli/configure`
* remove `check-env` and `check-root` scripts

diff --git a/bin/signal-cli/install b/bin/signal-cli/install
--- a/bin/signal-cli/install
+++ b/bin/signal-cli/install
@@ -2,8 +2,15 @@
 
 cd `dirname "$0"` # cd to script path
 
-./check-env SIGNAL_CLI_VERSION $SIGNAL_CLI_VERSION || exit $?
-./check-env CHANNEL_PHONE_NUMBER $CHANNEL_PHONE_NUMBER || exit $?
+if [ -z $SIGNAL_CLI_VERSION ];then
+  echo "--- ERROR: no SIGNAL_CLI_VERSION found. try \`\$ source .env\`"
+  exit 1
+fi
+
+if [ -z $CHANNEL_PHONE_NUMBER ];then
+  echo "--- ERROR: no CHANNEL_PHONE_NUMBER found. try \`\$ source .env\`"
+  exit 1
+fi
 
 echo "--- installing system dependencies"
 
