[118] read SIGNALBOOST_HOST_URL from ngrok in dev mode
* instead of paying to define a static subdomain on ngrok, allow ngrok
  to assign us a dynamic public url on every run
* use the ngrok API to fetch the public url, then assign it to `SIGNALBOOST_HOST_URL`
  * do this in `bin/entrypoint/app` to pass the url to the signalboost
    application server
  * do it in `cli/boost-commands/_check-env` to pass it to the `boost`
    cli command
* env file changes:
  * we no longer need `SIGNALBOOST_HOST_URL` in `.env.dev` (b/c we
    will define it by querying ngrok!)
  * we no longer need ANY ngrok env vars (because an ngrok account is
    no longer needed to run signalboost in dev mode! yay!!!)
  * we introduce `SIGNALBOOST_ENV` env var to help tooling scripts
    development and production modes (useful for figuring out whether
    to query ngrok to define an undefined value for `SIGNALBOOST_HOST_URL`)

usage:

for these changes to work, devs should run:

```
cd path/to/signalboost
git checkout master
git pull origin master
make docker.build
./bin/blackbox/shread_all_files
./bin/blackbox/decrypt_all_files
```

diff --git a/cli/boost-commands/_check-env b/cli/boost-commands/_check-env
--- a/cli/boost-commands/_check-env
+++ b/cli/boost-commands/_check-env
@@ -36,8 +36,22 @@ check-env(){
   fi
 
   if [[ -z ${SIGNALBOOST_HOST_URL} ]];then
-    echo "--- ERROR: no SIGNALBOOST_HOST_URL found in the .env file in ${env_file}"
-    exit 1
+
+    if [[ ${SIGNALBOOST_ENV} != "production" ]];then
+      # fetch the ngrok public url, then strip the everything but the domain name (ie: schema, quotes, etc.)
+      host_url=$(curl -s localhost:4040/api/tunnels | jq ".tunnels[0].public_url" | cut -c 9- | rev | cut -c 2- | rev)
+
+      if [[ -z ${host_url} ]];then
+        echo "Sorry, you are trying to run boost against a local dev server, but ngrok does not appear to be running."
+        echo "That means we cannot find a proxy to route requests through. Please troubleshoot ngrok and try again!"
+        exit 1
+      fi
+      export SIGNALBOOST_HOST_URL=${host_url}
+
+      else
+      echo "--- ERROR: no SIGNALBOOST_HOST_URL found in the .env file in ${env_file}"
+      exit 1
+    fi
   fi
 
   if [[ -z ${TWILIO_ACCOUNT_SID} ]];then
