[447] don't require channel phone number in `boost create-channel`
(side-effect)

channel phone number is no longer required, so allow it to be null in `boost`!

diff --git a/cli/boost-commands/create-channel b/cli/boost-commands/create-channel
--- a/cli/boost-commands/create-channel
+++ b/cli/boost-commands/create-channel
@@ -31,9 +31,11 @@ done
 source ./_check-env
 check-env ${env_file}
 
-if [[ ! $phone_number =~ ^\+[0-9]{9,15}$ ]];then
-  echo "> ERROR: -p must be a valid phone number prefixed by a country code"
-  exit 1
+if [[ ! -z "$phone_number" ]];then
+  if [[ ! $phone_number =~ ^\+[0-9]{9,15}$ ]];then
+    echo "> ERROR: -p must be a valid phone number prefixed by a country code"
+    exit 1
+  fi
 fi
 
 if [[ -z "$admins" ]]
