[100] restore trigger-trust behavior
* calling `trust` from signalboost command or cli doesn't actually
  work if no messages have been sent yet!
* so revert to just sending them a message with failing
  tests (boo!) (for now!)

diff --git a/cli/boost-commands/trust b/cli/boost-commands/trust
--- a/cli/boost-commands/trust
+++ b/cli/boost-commands/trust
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
 if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
-  echo "this command trusts all safety numbers associated with a user's phone number. valid options are:"
+  echo "this command trusts all safety numbers associated with a member phone number. valid options are:"
   echo ""
-  echo "-p : user phone number";
+  echo "-c: channel phone number (any phone number that user is a member of will work!)";
+  echo "-m: member phone number (required)";
   echo "-u : url to target (in dev, use signalboost.ngrok.io)";
   echo ""
   exit 1
@@ -16,10 +17,13 @@ if [ -z $SIGNALBOOST_API_TOKEN ];then
   exit 1
 fi
 
-while getopts ":p:n:s:u:" opt; do
+while getopts ":c:m:u:" opt; do
   case "$opt" in
-    p)
-      phone_number="$OPTARG"
+    c)
+      channel_phone_number="$OPTARG"
+      ;;
+    m)
+      member_phone_number="$OPTARG"
       ;;
     u)
       url="$OPTARG"
@@ -27,10 +31,16 @@ while getopts ":p:n:s:u:" opt; do
   esac
 done
 
-if [[ ! $phone_number =~ ^\+(1|52)[0-9]{10}$ ]];then
+if [[ ! $channel_phone_number =~ ^\+(1|52)[0-9]{10}$ ]];then
   echo "> ERROR: -p must be a 10 digit phone number prefixed by a country code (+1 or +52)"
   exit 1
 fi
+
+if [[ ! $member_phone_number =~ ^\+(1|52)[0-9]{10}$ ]];then
+  echo "> ERROR: -p must be a 10 digit phone number prefixed by a country code (+1 or +52)"
+  exit 1
+fi
+
 
 if [ -z $url ];then url=${SIGNALBOOST_HOST_URL}; fi
 
@@ -39,5 +49,5 @@ echo "--- trusting all safety numbers for user ${phone_number} at url ${url}"
 curl -s -X POST \
      -H "Content-Type: application/json" \
      -H "Token: $SIGNALBOOST_API_TOKEN" \
-     -d "{ \"memberPhoneNumber\": \"$phone_number\" }" \
+     -d "{ \"channelPhoneNumber\": \"$channel_phone_number\", \"memberPhoneNumber\": \"$member_phone_number\" }" \
      https://${url}/phoneNumbers/trust | jq
