[201] Add sigarillo configuration to load tests.

diff --git a/bin/load/run b/bin/load/run
--- a/bin/load/run
+++ b/bin/load/run
@@ -5,7 +5,6 @@ cd `dirname "$0"` # cd to script path
 cd ../.. # cd to project root
 
 check-until-ngrok-url-available(){
-  echo "checking orchestrator ngrok..."
   # fetch the ngrok public url, then strip the everything but the domain name (ie: schema, quotes, etc.)
 
   if [[ "$(uname)" == 'Darwin' ]]
@@ -30,36 +29,54 @@ check-until-ngrok-url-available(){
 
 ### START DB
 
-echo "--- setting up signal-server database..."
-docker-compose -f docker-compose-test-load.yml up -d db
+echo "--- SETUP: setting up service databases..."
+docker-compose -f docker-compose-test-load.yml up -d db 2>/dev/null 1>&2
 
 sleep 2
 
 ### MIGRATIONS
 
-psql postgresql://postgres@localhost:5432 -c "CREATE USER signal WITH PASSWORD 'password';"
-psql postgresql://postgres@localhost:5432 -c "CREATE DATABASE signal;"
+#### signal-server
+psql -q postgresql://postgres@localhost:5432 -c "CREATE USER signal WITH PASSWORD 'password';" 2>/dev/null 1>&2
+psql -q postgresql://postgres@localhost:5432 -c "CREATE DATABASE signal;" 2>/dev/null 1>&2
+psql -q "postgresql://localhost:5432/signal?user=signal&password=password" -f ./simulator/files/db_100_accounts.sql 2>/dev/null 1>&2
 
-docker-compose -f docker-compose-test-load.yml run --entrypoint /signalboost/bin/db/setup app
+#### sigarillo
+psql -q postgresql://postgres@localhost:5432 -c "CREATE USER sigarillo WITH PASSWORD 'sigarillo';" 2>/dev/null 1>&2
+psql -q postgresql://postgres@localhost:5432 -c "CREATE DATABASE sigarillo;" 2>/dev/null 1>&2
+
+#### signalboost
+docker-compose -f docker-compose-test-load.yml run --entrypoint /signalboost/bin/db/setup app 2>/dev/null 1>&2
 
 ### RUN SERVICES
 
-echo "--- running load test..."
-docker-compose -f docker-compose-test-load.yml up -d signal_server redis ngrok_simulator signalboost_ngrok app simulator
+echo "--- SETUP: starting load test services..."
+docker-compose -f docker-compose-test-load.yml up -d signal_server redis ngrok_simulator signalboost_ngrok 2>/dev/null 1>&2
 
 check-until-ngrok-url-available
-echo "NGROK URL: $host_url"
+host_url="sb-load.loca.lt"
 
-echo "--- building signald with local SIGNAL_URL..."
+echo "--- SETUP: building signald with local SIGNAL_URL..."
 
-docker build --build-arg SIGNAL_URL=${host_url} -t team-friendo/signalboost/signald:load -f ./docker/signald.dockerfile .
+docker build --build-arg SIGNAL_URL=${host_url} -t team-friendo/signalboost/signald:load -f ./docker/signald.dockerfile . 2>/dev/null 1>&2
 
-docker-compose -f docker-compose-test-load.yml up -d signald_app signald_simulator
+echo "--- RUN: starting signald for app + simulator..."
+# docker-compose -f docker-compose-test-load.yml up -d signald_app signald_simulator localtunnel
+docker-compose -f docker-compose-test-load.yml up -d localtunnel sigarillo 2>/dev/null 1>&2
+
+### RUN SIMULATOR
+
+# echo "--- RUN: starting simulator"
+# docker-compose -f docker-compose-test-load.yml up -d simulator
+
+### RUN LOAD TEST
+
+# docker-compose -f docker-compose-test-load.yml run --entrypoint /signalboost/bin/entrypoint/app-load app
 
 ### STOP SERVICES
 
-echo "--- stopping load test..."
+# echo "--- CLEANUP: stopping load test services..."
 # docker-compose -f docker-compose-test-load.yml down
-echo "--- DONE!"
+# echo "--- DONE!"
 
 popd
